# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/e7936fa3-7f71-4593-942a-5ca0187cd599";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/40FB-E015";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
    "/mnt/extra" = {
      device = "/dev/disk/by-uuid/63979a69-2d7f-4f09-8a8f-6c2b6b9a26bf";
      fsType = "ext4";
    };
    "/mnt/astore" = {
      device = "//192.168.200.240/astore";
      fsType = "cifs";
      options = [
        "credentials=${config.sops.secrets.samba.path}"
        "uid=1000" # for some reason, UID isn't set by users.users
        "gid=${toString config.users.groups.users.gid}"
        "x-systemd.automount"
        "noauto"
      ];
    };
    "/mnt/share" = {
      device = "//192.168.200.240/share";
      fsType = "cifs";
      options = [
        "credentials=${config.sops.secrets.samba.path}"
        "uid=1000" # for some reason, UID isn't set by users.users
        "gid=${toString config.users.groups.users.gid}"
        "x-systemd.automount"
        "noauto"
      ];
    };
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/718cb90b-1744-4e02-853c-6ba26ffd4289"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
